apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ jenkins_ns }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ jenkins_app }}
  template:
    metadata:
      labels:
        app: {{ jenkins_app }}
    spec:
      securityContext:
            fsGroup: 1000
            runAsUser: 1000
      serviceAccountName: "{{ jenkins_admin_acct }}"
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          resources:
            limits:
              memory: "{{ jenkins_app_mem_limit }}"
              cpu: "{{ jenkins_app_cpu_limit }}"
            requests:
              memory: "{{ jenkins_app_mem_req }}"
              cpu: "{{ jenkins_app_cpu_req }}"
          ports:
            - name: httpport
              containerPort: {{ jenkins_app_http_port }}
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: {{ jenkins_app_http_port }}
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: {{ jenkins_app_http_port }}
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: {{ jenkins_pvc_name }}
