---
- name: Provision virtual machines
  hosts: vmhost
  become: true
  roles:
    - role: virtualization-checks
    - role: virtualization-packages
    - role: virtualization-services
    - role: prepare-vm-host
    - role: download-vm-image
    - role: provision-vm-network
    - role: provision-vm
