apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ jenkins_pvc_name }}
  namespace: {{ jenkins_ns }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ jenkins_pvc_size }}
